// src/components/ApiSettings.vue
<script setup lang="ts">
import { ref } from "vue";
import { useDocumentStore } from "../stores/document";
import { storeToRefs } from "pinia";

const store = useDocumentStore();
const { apiConfig, error } = storeToRefs(store);

const testResult = ref<{ type: "success" | "failure"; message: string } | null>(null);
const testing = ref(false);

const PROVIDERS = [
  { value: "openai", label: "OpenAI" },
  { value: "claude", label: "Anthropic Claude" },
  { value: "deepseek", label: "DeepSeek" },
  { value: "custom", label: "自定义" },
];

const PROVIDER_URLS: Record<string, string> = {
  openai: "https://api.openai.com/v1/chat/completions",
  claude: "https://api.anthropic.com",
  deepseek: "https://api.deepseek.com",
};

function onProviderChange(value: string) {
  if (value !== "custom" && PROVIDER_URLS[value]) {
    apiConfig.value.api_url = PROVIDER_URLS[value];
  }
}

async function handleSave() {
  await store.saveApiConfig(apiConfig.value);
}

async function handleTest() {
  testing.value = true;
  testResult.value = null;
  try {
    // 先保存再测试
    await store.saveApiConfig(apiConfig.value);
    const result = await store.testApiConnection();
    testResult.value = { type: "success", message: result };
  } catch (err) {
    testResult.value = { type: "failure", message: String(err) };
  } finally {
    testing.value = false;
  }
}
</script>

<template>
  <div class="space-y-4">
    <h3 class="text-sm font-semibold text-gray-400 uppercase tracking-wider">
      API 设置
    </h3>

    <!-- AI 提供商 -->
    <div>
      <label class="block text-xs text-gray-500 mb-1">AI 提供商</label>
      <select
        v-model="apiConfig.provider"
        class="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-200 focus:border-blue-500 focus:outline-none"
        @change="onProviderChange(($event.target as HTMLSelectElement).value)"
      >
        <option
          v-for="p in PROVIDERS"
          :key="p.value"
          :value="p.value"
        >
          {{ p.label }}
        </option>
      </select>
    </div>

    <!-- API 密钥 -->
    <div>
      <label class="block text-xs text-gray-500 mb-1">API 密钥</label>
      <input
        v-model="apiConfig.api_key"
        type="password"
        class="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-200 font-mono focus:border-blue-500 focus:outline-none"
        placeholder="sk-..."
      />
    </div>

    <!-- API 地址 -->
    <div>
      <label class="block text-xs text-gray-500 mb-1">API 地址</label>
      <input
        v-model="apiConfig.api_url"
        type="text"
        class="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-200 font-mono focus:border-blue-500 focus:outline-none"
      />
      <p class="text-xs text-gray-600 mt-1">
        {{ apiConfig.provider === "claude" ? "Claude 使用 /v1/messages" : "OpenAI 兼容格式 /v1/chat/completions" }}
      </p>
    </div>

    <!-- 模型 -->
    <div>
      <label class="block text-xs text-gray-500 mb-1">模型</label>
      <input
        v-model="apiConfig.model"
        type="text"
        class="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-200 font-mono focus:border-blue-500 focus:outline-none"
        :placeholder="apiConfig.provider === 'claude' ? 'claude-sonnet-4-20250514' : 'gpt-4o'"
      />
    </div>

    <!-- 操作按钮 -->
    <div class="flex gap-2">
      <button
        class="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm rounded-lg transition-colors"
        @click="handleSave"
      >
        保存设置
      </button>
      <button
        class="px-4 py-2 bg-gray-700 hover:bg-gray-600 disabled:opacity-50 text-gray-200 text-sm rounded-lg transition-colors"
        :disabled="testing"
        @click="handleTest"
      >
        {{ testing ? "测试中..." : "测试连接" }}
      </button>
    </div>

    <!-- 测试结果 -->
    <div
      v-if="testResult"
      class="text-sm p-3 rounded-lg"
      :class="{
        'bg-green-950/50 border border-green-800 text-green-300': testResult.type === 'success',
        'bg-red-950/50 border border-red-800 text-red-300': testResult.type === 'failure',
      }"
    >
      <p class="whitespace-pre-wrap">{{ testResult.message }}</p>
    </div>

    <!-- 全局错误 -->
    <div
      v-if="error"
      class="text-sm text-red-400 bg-red-950/30 border border-red-900/30 rounded-lg px-3 py-2"
    >
      {{ error }}
    </div>
  </div>
</template>

// src/components/Settings/ApiSettings.tsx
import { useState, useEffect } from "react";
import { invoke } from "@tauri-apps/api/core";

interface ProviderPreset {
  name: string;
  label: string;
  apiUrl: string;
  models: { value: string; label: string }[];
}

const PRESETS: Record<string, ProviderPreset> = {
  openai: {
    name: "openai",
    label: "OpenAI",
    apiUrl: "https://api.openai.com/v1/chat/completions",
    models: [
      { value: "gpt-4o", label: "GPT-4o" },
      { value: "gpt-4o-mini", label: "GPT-4o Mini" },
      { value: "gpt-4-turbo", label: "GPT-4 Turbo" },
    ],
  },
  deepseek: {
    name: "deepseek",
    label: "DeepSeek",
    apiUrl: "https://api.deepseek.com/v1/chat/completions",
    models: [
      { value: "deepseek-v4-flash", label: "DeepSeek V4 Flash (1M 上下文)" },
      { value: "deepseek-v4-pro", label: "DeepSeek V4 Pro (1M 上下文)" },
    ],
  },
  claude: {
    name: "claude",
    label: "Anthropic Claude",
    apiUrl: "https://api.anthropic.com/v1/messages",
    models: [
      { value: "claude-sonnet-4-20250514", label: "Claude Sonnet 4" },
      { value: "claude-haiku-3-5-20241022", label: "Claude Haiku 3.5" },
    ],
  },
  siliconflow: {
    name: "siliconflow",
    label: "SiliconFlow (硅基流动)",
    apiUrl: "https://api.siliconflow.cn/v1/chat/completions",
    models: [
      { value: "deepseek-ai/DeepSeek-V3", label: "DeepSeek V3 (硅基)" },
      { value: "deepseek-ai/DeepSeek-R1", label: "DeepSeek R1 (硅基)" },
      { value: "Qwen/Qwen2.5-72B-Instruct", label: "Qwen 2.5 72B" },
    ],
  },
};

export default function ApiSettings() {
  const [apiKey, setApiKey] = useState("");
  const [apiUrl, setApiUrl] = useState("https://api.openai.com/v1/chat/completions");
  const [model, setModel] = useState("gpt-4o");
  const [provider, setProvider] = useState("openai");
  const [testResult, setTestResult] = useState("");
  const [testing, setTesting] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    loadConfig();
  }, []);

  const loadConfig = async () => {
    try {
      const cfg = await invoke<{ api_key: string; api_url: string; model: string }>("get_api_config");
      setApiKey(cfg.api_key);
      setApiUrl(cfg.api_url);
      setModel(cfg.model);
      // 尝试匹配预设
      for (const [key, p] of Object.entries(PRESETS)) {
        if (cfg.api_url.includes(p.apiUrl.replace(/^https?:\/\//, "").replace(/\/v1\/.*$/, ""))) {
          setProvider(key);
          break;
        }
      }
    } catch (err) {
      console.error("加载配置失败:", err);
    }
  };

  const handleProviderChange = (providerName: string) => {
    setProvider(providerName);
    if (providerName === "custom") return;
    const preset = PRESETS[providerName];
    if (preset) {
      setApiUrl(preset.apiUrl);
      if (preset.models.length > 0) {
        setModel(preset.models[0].value);
      }
    }
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await invoke("set_api_config", { apiKey, apiUrl, model });
      setTestResult("✅ 配置已保存");
    } catch (err) {
      setTestResult("❌ 保存失败: " + String(err));
    } finally {
      setSaving(false);
    }
  };

  const handleTest = async () => {
    setTesting(true);
    setTestResult("");
    try {
      await invoke("set_api_config", { apiKey, apiUrl, model });
      const res = await invoke<string>("test_api_connection");
      setTestResult(res);
    } catch (err) {
      setTestResult("❌ " + String(err));
    } finally {
      setTesting(false);
    }
  };

  const currentPreset = PRESETS[provider];
  const models = currentPreset?.models ?? [];

  return (
    <div className="api-settings">
      <h3>⚙️ API 配置</h3>

      <div className="form-group">
        <label>服务商</label>
        <select
          value={provider}
          onChange={(e) => handleProviderChange(e.target.value)}
          className="form-input"
        >
          <option value="openai">OpenAI</option>
          <option value="deepseek">DeepSeek</option>
          <option value="claude">Anthropic Claude</option>
          <option value="siliconflow">SiliconFlow (硅基流动)</option>
          <option value="custom">自定义</option>
        </select>
      </div>

      <div className="form-group">
        <label>API 密钥</label>
        <input
          type="password"
          value={apiKey}
          onChange={(e) => setApiKey(e.target.value)}
          placeholder={provider === "deepseek" ? "sk-..." : provider === "claude" ? "sk-ant-..." : "输入 API 密钥"}
          className="form-input"
        />
      </div>

      <div className="form-group">
        <label>API 地址</label>
        <input
          type="text"
          value={apiUrl}
          onChange={(e) => {
            setApiUrl(e.target.value);
            setProvider("custom");
          }}
          placeholder="https://api.openai.com/v1/chat/completions"
          className="form-input"
        />
      </div>

      <div className="form-group">
        <label>模型</label>
        {models.length > 0 ? (
          <select
            value={model}
            onChange={(e) => setModel(e.target.value)}
            className="form-input"
          >
            {models.map((m) => (
              <option key={m.value} value={m.value}>{m.label}</option>
            ))}
          </select>
        ) : (
          <input
            type="text"
            value={model}
            onChange={(e) => setModel(e.target.value)}
            placeholder="输入模型名称"
            className="form-input"
          />
        )}
      </div>

      <div className="settings-actions">
        <button onClick={handleSave} disabled={saving} className="btn-primary">
          {saving ? "保存中..." : "💾 保存"}
        </button>
        <button onClick={handleTest} disabled={testing} className="btn-secondary">
          {testing ? "测试中..." : "🔗 测试连接"}
        </button>
      </div>

      {testResult && (
        <div className={`test-result ${testResult.startsWith("✅") ? "success" : "failure"}`}>
          {testResult.includes("\n") ? (
            <pre className="error-detail">{testResult}</pre>
          ) : (
            testResult
          )}
        </div>
      )}
    </div>
  );
}
